version: '3'

services:
  mongodb:
    image: mongo:7.0.7
    tty: true
    ports:
      - "27017:27017"

  app:
    build: .
    tty: true
    ports:
      - "5055:5055"
    command: sh -c "node seeder.js && npm start"
    depends_on:
      - mongodb