const productData = [
  {
    name: "Zunkel Schwarz",
    brand: "Blast",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dicta ad culpa quas nam minima odit, amet autem, iure harum nisi assumenda vitae ut maxime, id porro veritatis similique? Blanditiis, obcaecati",
    parent: "Furniture",
    keyword: "FURNITURE",
    children: "Chair",
    imageUrl: ["/product/1.jpg", "/product/1-2.jpg"],
    originalPrice: 80,
    discount: 33,
    price: 100,
    productClass: "Hot",
    sku: "D2300-3-2-1",
    stocks: [
      {
        size: "L",
        color: "blue",
        material: "scarlet",
        quantity: 100,
        imageUrl: ["/product/1.jpg", "/product/1-2.jpg"],
      },
      {
        size: "M",
        color: "black",
        material: "scarlet",
        quantity: 100,
        imageUrl: ["/product/1.jpg", "/product/1-2.jpg"],
      },
      {
        size: "S",
        color: "white",
        material: "scarlet",
        quantity: 100,
        imageUrl: ["/product/1.jpg", "/product/1-2.jpg"],
      },
    ],
  },
  {
    name: "Namaste Vase",
    brand: "Minimal",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dicta ad culpa quas nam minima odit, amet autem, iure harum nisi assumenda vitae ut maxime, id porro veritatis similique? Blanditiis, obcaecati",
    parent: "Bed & Bath",
    keyword: "BED_BATH",
    children: "Vase",
    imageUrl: ["/product/2.jpg", "/product/2-2.jpg"],
    originalPrice: 80,
    discount: 0,
    price: 200.0,
    productClass: "Hot",
    sku: "D2300-3-2-2",
    stocks: [
      {
        size: "L",
        color: "blue",
        material: "ceramic",
        quantity: 100,
        imageUrl: ["/product/2.jpg", "/product/2-2.jpg"],
      },
      {
        size: "M",
        color: "black",
        material: "ceramic",
        quantity: 100,
        imageUrl: ["/product/2.jpg", "/product/2-2.jpg"],
      },
      {
        size: "S",
        color: "white",
        material: "ceramic",
        quantity: 100,
        imageUrl: ["/product/2.jpg", "/product/2-2.jpg"],
      },
    ],
  },
  {
    name: "Chair Oak Matt Lacquered",
    brand: "Money",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dicta ad culpa quas nam minima odit, amet autem, iure harum nisi assumenda vitae ut maxime, id porro veritatis similique? Blanditiis, obcaecati",
    parent: "Furniture",
    keyword: "FURNITURE",
    children: "Chair",
    imageUrl: ["/product/3.jpg", "/product/3-2.jpg"],
    originalPrice: 80,
    discount: 0,
    price: 150.0,
    productClass: "Hot",
    sku: "D2300-3-2-3",
    stocks: [
      {
        size: "L",
        color: "blue",
        material: "scarlet",
        quantity: 100,
        imageUrl: ["/product/3.jpg", "/product/3-2.jpg"],
      },
      {
        size: "M",
        color: "black",
        material: "scarlet",
        quantity: 100,
        imageUrl: ["/product/3.jpg", "/product/3-2.jpg"],
      },
      {
        size: "S",
        color: "white",
        material: "scarlet",
        quantity: 100,
        imageUrl: ["/product/3.jpg", "/product/3-2.jpg"],
      },
    ],
  },
  {
    name: "Amp Pendant Light Large",
    brand: "Beat Sound",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dicta ad culpa quas nam minima odit, amet autem, iure harum nisi assumenda vitae ut maxime, id porro veritatis similique? Blanditiis, obcaecati",
    parent: "Lighting",
    keyword: "LIGHTING",
    children: "Table",
    imageUrl: ["/product/5.jpg", "/product/5-2.jpg"],
    originalPrice: 80,
    discount: 7,
    price: 150.0,
    sku: "D2300-3-2-4",
    stocks: [
      {
        size: "L",
        color: "blue",
        material: "scarlet",
        quantity: 100,
        imageUrl: ["/product/5.jpg", "/product/5-2.jpg"],
      },
      {
        size: "M",
        color: "black",
        material: "scarlet",
        quantity: 100,
        imageUrl: ["/product/5.jpg", "/product/5-2.jpg"],
      },
      {
        size: "S",
        color: "white",
        material: "scarlet",
        quantity: 100,
        imageUrl: ["/product/5.jpg", "/product/5-2.jpg"],
      },
    ],
  },
  {
    name: "Bora Armchair",
    brand: "Red box",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dicta ad culpa quas nam minima odit, amet autem, iure harum nisi assumenda vitae ut maxime, id porro veritatis similique? Blanditiis, obcaecati",
    parent: "Furniture",
    keyword: "FURNITURE",
    children: "Chair",
    imageUrl: ["/product/9.jpg", "/product/9-2.jpg", "/product/9-3.jpg"],
    originalPrice: 100,
    discount: 10,
    price: 90,
    sku: "D2300-3-2-4",
    stocks: [
      {
        size: "L",
        color: "blue",
        material: "scarlet",
        quantity: 100,
        imageUrl: ["/product/9.jpg", "/product/9-2.jpg", "/product/9-3.jpg"],
      },
      {
        size: "M",
        color: "black",
        material: "scarlet",
        quantity: 100,
        imageUrl: ["/product/9.jpg", "/product/9-2.jpg", "/product/9-3.jpg"],
      },
      {
        size: "S",
        color: "white",
        material: "scarlet",
        quantity: 100,
        imageUrl: ["/product/9.jpg", "/product/9-2.jpg", "/product/9-3.jpg"],
      },
    ],
  },
  {
    name: "Mahmud Colpus",
    brand: "Red box",
    description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    parent: "Office",
    keyword: "OFFICE",
    children: "Table",
    imageUrl: ["/product/6.jpg", "/product/6-2.jpg"],
    originalPrice: 869.81,
    discount: 2,
    price: 968.2,
    productClass: "",
    sku: "D2300-3-2-1",
    stocks: [
      {
        size: "L",
        color: "blue",
        material: "Wood, plastic",
        quantity: 141,
        imageUrl: ["/product/6.jpg", "/product/6-2.jpg"],
      },
      {
        size: "M",
        color: "black",
        material: "Wood, plastic",
        quantity: 256,
        imageUrl: ["/product/6.jpg", "/product/6-2.jpg"],
      },
      {
        size: "S",
        color: "white",
        material: "Wood, plastic",
        quantity: 862,
        imageUrl: ["/product/6.jpg", "/product/6-2.jpg"],
      },
    ],
  },
  {
    name: "Randa Perceval",
    brand: "Minimal",
    description:
      "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    parent: "Furniture",
    keyword: "FURNITURE",
    children: "Sofa",
    imageUrl: ["/product/7.jpg", "/product/7-2.jpg"],
    originalPrice: 464.24,
    discount: 73,
    price: 769.31,
    productClass: "",
    sku: "D2300-3-2-1",
    stocks: [
      {
        size: "L",
        color: "blue",
        material: "Scarlet",
        quantity: 141,
        imageUrl: ["/product/7.jpg", "/product/7-2.jpg"],
      },
      {
        size: "M",
        color: "black",
        material: "Scarlet",
        quantity: 256,
        imageUrl: ["/product/7.jpg", "/product/7-2.jpg"],
      },
      {
        size: "S",
        color: "white",
        material: "Scarlet",
        quantity: 862,
        imageUrl: ["/product/7.jpg", "/product/7-2.jpg"],
      },
    ],
  },
  {
    name: "SPINNING PENDANT LAMP",
    brand: "Blast",
    description:
      "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    parent: "Lighting",
    keyword: "LIGHTING",
    children: "Lamp",
    imageUrl: ["/product/8.jpg", "/product/8-2.jpg"],
    originalPrice: 31.2,
    discount: 92,
    price: 787.46,
    productClass: "",
    sku: "D2300-3-2-1",
    stocks: [
      {
        size: "L",
        color: "blue",
        material: "Plastic",
        quantity: 141,
        imageUrl: ["/product/8.jpg", "/product/8-2.jpg"],
      },
      {
        size: "M",
        color: "black",
        material: "Plastic",
        quantity: 256,
        imageUrl: ["/product/8.jpg", "/product/8-2.jpg"],
      },
      {
        size: "S",
        color: "white",
        material: "Plastic",
        quantity: 862,
        imageUrl: ["/product/8.jpg", "/product/8-2.jpg"],
      },
    ],
  },
  {
    name: "Janessa Pyatt",
    brand: "Money",
    description: "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
    parent: "Outdoor",
    keyword: "OUTDOOR",
    children: "Table",
    imageUrl: ["/product/10.jpg", "/product/10-2.jpg"],
    originalPrice: 458.8,
    discount: 41,
    price: 635.6,
    productClass: "",
    sku: "D2300-3-2-1",
    stocks: [
      {
        size: "L",
        color: "blue",
        material: "Plastic",
        quantity: 685,
        imageUrl: ["/product/10.jpg", "/product/10-2.jpg"],
      },
      {
        size: "M",
        color: "black",
        material: "Plastic",
        quantity: 100,
        imageUrl: ["/product/10.jpg", "/product/10-2.jpg"],
      },
    ],
  },
  {
    name: "KITTCHEN TABLE",
    brand: "Blast",
    description:
      "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    parent: "Office",
    keyword: "OFFICE",
    children: "Table",
    imageUrl: ["/product/11.jpg", "/product/11-2.jpg"],
    originalPrice: 932.63,
    discount: 56,
    price: 11.04,
    productClass: "",
    sku: "D2300-3-2-1",
    stocks: [
      {
        size: "L",
        color: "blue",
        material: "Wood, plastic",
        quantity: 602,
        imageUrl: ["/product/11.jpg", "/product/11-2.jpg"],
      },
      {
        size: "M",
        color: "blue",
        material: "Wood, plastic",
        quantity: 982,
        imageUrl: ["/product/11.jpg", "/product/11-2.jpg"],
      },
      {
        size: "L",
        color: "black",
        material: "Wood, plastic",
        quantity: 207,
        imageUrl: ["/product/11.jpg", "/product/11-2.jpg"],
      },
    ],
  },
  {
    name: "Ethelyn Tomaello",
    brand: "Beat Sound",
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    parent: "Outdoor",
    keyword: "OUTDOOR",
    children: "Table",
    imageUrl: ["/product/12.jpg", "/product/12-2.jpg"],
    originalPrice: 366.04,
    discount: 97,
    price: 395.21,
    productClass: "",
    sku: "D2300-3-2-1",
    stocks: [
      {
        size: "L",
        color: "blue",
        material: "Plastic",
        quantity: 141,
        imageUrl: ["/product/12.jpg", "/product/12-2.jpg"],
      },
      {
        size: "M",
        color: "black",
        material: "Plastic",
        quantity: 256,
        imageUrl: ["/product/12.jpg", "/product/12-2.jpg"],
      },
      {
        size: "S",
        color: "white",
        material: "Plastic",
        quantity: 862,
        imageUrl: ["/product/12.jpg", "/product/12-2.jpg"],
      },
    ],
  },
];

export default productData;
